[tool.poetry]
name = "grai-graph"
version = "0.1.0"
description = ""
authors = ["Ian Eaves <ian.k.eaves@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.8.3"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
