name: MySQL Integration CI
on:
  pull_request:
    paths:
    - "grai-integrations/source-mysql/**"
env:
  py_ver: "3.10"
  poetry_ver: "1.2.2"
  project_dir: "grai-integrations/source-mysql"

jobs:
  lint-integration-mysql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Install Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ env.py_ver }}"

    - run: pip install black isort

    - run: |
        black . --check
        isort . --profile black

  tests-integration-mysql:
    needs: lint-integration-mysql
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    services:
      test_db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: grai
          MYSQL_USER: grai
          MYSQL_PASSWORD: grai
          MYSQL_DATABASE: grai
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "${{ env.py_ver }}"

    - run: |
        pip install pytest
        pip install .

    - run: pytest
